# Generated by Django 2.2.20 on 2021-06-06 11:46
from property.models import Owner
from django.db import migrations


def copy_owners_from_flat_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats:
        Owner.objects.get_or_create(owner=flat.owner,
                                    owners_phonenumber=flat.owners_phonenumber,
                                    defaults={
                                        'owner_pure_phone': flat.owner_pure_phone,
                                    })


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_owner'),
    ]

    operations = [
        migrations.RunPython(copy_owners_from_flat_owner)
    ]
